// /*
// Auto-generated by: https://github.com/pmndrs/gltfjsx
// */

// import React, { useRef } from 'react'
// import { useGLTF } from '@react-three/drei'

// export function Model(props: any) {
//   const { nodes, materials } = useGLTF('/earth.glb')
//   return (
//     <group {...props} dispose={null}>
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes.Cube001.geometry}
//         material={materials['Default OBJ']}
//       />
//     </group>
//   )
// }

// useGLTF.preload('/earth.glb')
